apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      app: petclinic
  template:
    spec:
      containers:
        - name: petclinic
          env:
            - name: SPLUNK_OTEL_AGENT
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(SPLUNK_OTEL_AGENT):4317"
            - name: OTEL_SERVICE_NAME
              value: "petclinic"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "deployment.environment=dev"
