apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  labels:
    app: petclinic
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: ismapro/instrumented-petclinic-app:latest
        env:
          - name: SPLUNK_OTEL_AGENT
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: SPLUNK_METRICS_ENDPOINT
            value: "http://$(SPLUNK_OTEL_AGENT):9943"
            #value: "http://$(SPLUNK_OTEL_AGENT):9080/v2/datapoint"        
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://$(SPLUNK_OTEL_AGENT):4317"
          - name: OTEL_SERVICE_NAME
            value: "petclinic"
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: "deployment.environment=dev"
          - name: SPLUNK_METRICS_EXPORT_INTERVAL
            value: "10s"
          - name: spring.datasource.url
            value: "jdbc:postgresql://postgres/petclinic"
          - name: spring.datasource.username
            value: "petclinic"
          - name: spring.datasource.password
            value: "petclinic"    
        ports:
        - containerPort: 8080
